name: Grade Management - build

on:
  push:
    paths:
      - "grade-management/**"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: "Run dotnet build"
        working-directory: grade-management
        run: |
          dotnet build
          dotnet test
