name: Review UI - build

on:
  push:
    paths:
      - "review-ui/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: "Run dotnet build"
        working-directory: review-ui
        run: |
          dotnet build
          dotnet test
